Fix bugs
AY2223S1-CS2103T-T17-2/tp pull request #146
Opened 2022-10-29 09:30 UTC by TanPingZhi

- [ ] Update Calorie's vague constraints
- [ ] Update possible arguments for locate in UG
- [ ]

2022-10-30 07:00 UTC, xav168 requested changes

2022-10-30 07:00 UTC, xav168 commented on src/main/java/seedu/nutrigoals/model/Calorie.java
> +        "Calorie must take on an integer in between 0 and 2,147,483,647 inclusively";
Not sure if we are allowed to change this

2022-10-30 10:24 UTC, ruiqi7 commented on src/main/java/seedu/nutrigoals/logic/parser/ParserUtil.java
> +        out.put("VENTUS", new Location("VENTUS", "1.295314453199568, 103.77019611100641"));
Not sure if we can add these, but to address the feature flaw mentioned by the tester, could perhaps mention in the UG that more locations will be added in future releases~ (can refer to the food items section for the `find` command in the UG for an example)

2022-11-01 02:53 UTC, TanPingZhi commented on src/main/java/seedu/nutrigoals/logic/commands/LocateGymCommand.java
> +        + "Parameters: COM2 | S13 | S17 | CLB | UHC | LT1 | LT9 | AS6\n"
This is the current locations in master

2022-11-01 07:57 UTC, nicolelim02 commented on docs/UserGuide.md
> +Parameters: COM2 | S13 | S17 | CLB | UHC | LT1 | LT9 | AS6
Is this supposed to be rendered as a table?

<img width="771" alt="Screenshot 2022-11-01 at 3 54 06 PM" src="https://user-images.githubusercontent.com/97275050/199185513-4109032a-8f3f-4e91-a31b-bc5945b8c2d3.png">

2022-11-01 07:57 UTC, nicolelim02 commented on docs/UserGuide.md
> +More nus locations will be added
```suggestion
More nus locations will be added.
```

2022-11-01 07:57 UTC, nicolelim02 commented on docs/DeveloperGuide.md
> +* `LocateGymCommand#execute()`: Retrieves and displays the user's information.
Is the description incorrect?

2022-11-01 08:35 UTC, xav168 approved these changes

2022-11-01 08:35 UTC, merged